### ISSUE TITLE
No ESP being made after running patcher

### ISSUE THREAD

**Issue by LewdManoSaurus** [halgari/HalgarisRPGLoot#1]
Getting this when running the executable through MO2:

"Loading Load Order
Found 101 activated mods
System.ArgumentExeception: Load order file had malformed line: {str}
at Mutagen.Bethesda.LoadOrder.ProcessLoadOrder(Stream stream)
at ClassBasedLootGenerator.Verbs.Generate.Execute()
Press <Enter> to exit..."

Also, I know that you prefer issues here on Github instead of on Nexus, but it may be helpful for users to scroll through comments there quickly and try to identify similar issues they may encounter. Might also get more people reporting.

**Comment by EzioTheDeadPoet** [comment]
This is fixed now, follow the instructions on the modpage.
