### ISSUE TITLE
Error with patcher

### ISSUE THREAD

**Issue by ricky01-star** [halgari/HalgarisRPGLoot#4]
Note: It worked before but I added 1 mod

```System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at HalgarisRPGLoot.Extensions.RandomItem[T](T[] itms) in C:\Users\ricky\AppData\Local\Temp\Synthesis\02983aa1-bd1a-428c-ba65-116377bf5f89\Git\e39b6ce7-ad3a-4af1-bf24-47d1f3f0b433\Runner\HalgarisRPGLoot\Extensions.cs:line 15
   at HalgarisRPGLoot.ArmorAnalyzer.<>c__DisplayClass46_0.<GenerateEnchantment>b__0() in C:\Users\ricky\AppData\Local\Temp\Synthesis\02983aa1-bd1a-428c-ba65-116377bf5f89\Git\e39b6ce7-ad3a-4af1-bf24-47d1f3f0b433\Runner\HalgarisRPGLoot\ArmorAnalyzer.cs:line 185
   at HalgarisRPGLoot.Extensions.Repeatedly[T](Func`1 f)+MoveNext() in C:\Users\ricky\AppData\Local\Temp\Synthesis\02983aa1-bd1a-428c-ba65-116377bf5f89\Git\e39b6ce7-ad3a-4af1-bf24-47d1f3f0b433\Runner\HalgarisRPGLoot\Extensions.cs:line 21
   at System.Linq.Enumerable.DistinctIterator`1.MoveNext()
   at System.Linq.Enumerable.EnumerablePartition`1.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at HalgarisRPGLoot.Extensions.Shuffle[T](IEnumerable`1 coll) in C:\Users\ricky\AppData\Local\Temp\Synthesis\02983aa1-bd1a-428c-ba65-116377bf5f89\Git\e39b6ce7-ad3a-4af1-bf24-47d1f3f0b433\Runner\HalgarisRPGLoot\Extensions.cs:line 26
   at HalgarisRPGLoot.ArmorAnalyzer.GenerateEnchantment(ResolvedListItem`2 item, String rarityName, Int32 rarityEnchCount) in C:\Users\ricky\AppData\Local\Temp\Synthesis\02983aa1-bd1a-428c-ba65-116377bf5f89\Git\e39b6ce7-ad3a-4af1-bf24-47d1f3f0b433\Runner\HalgarisRPGLoot\ArmorAnalyzer.cs:line 185
   at HalgarisRPGLoot.ArmorAnalyzer.Generate() in C:\Users\ricky\AppData\Local\Temp\Synthesis\02983aa1-bd1a-428c-ba65-116377bf5f89\Git\e39b6ce7-ad3a-4af1-bf24-47d1f3f0b433\Runner\HalgarisRPGLoot\ArmorAnalyzer.cs:line 149
   at HalgarisRPGLoot.Program.RunPatch(SynthesisState`2 state) in C:\Users\ricky\AppData\Local\Temp\Synthesis\02983aa1-bd1a-428c-ba65-116377bf5f89\Git\e39b6ce7-ad3a-4af1-bf24-47d1f3f0b433\Runner\HalgarisRPGLoot\Program.cs:line 41
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Patch[TMod,TModGetter](RunSynthesisMutagenPatcher settings, PatcherFunction`2 patcher, UserPreferences userPreferences)
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass4_0`2.<Patch>b__1(RunSynthesisMutagenPatcher settings)
Synthesis.Bethesda.Execution.CliUnsuccessfulRunException: Error running solution patcher```

**Comment by EzioTheDeadPoet** [comment]
please edit your comment to 
have the log 
like this for better readability (maybe edit your comment to not make another new comment out of it)
```
```log

your log output```
```

but the Issue is, as you mentioned yourself, the mod added since it doesn't seem to tag/catalog its weapons to fit the vanilla way of creating weapon records.
This means the mod in question would need a specific patcher to do that and/or would need to be updated to work that way. 

Ideally you could link the mod using `[Modname](Link)` so others can find the issue as well. and either remove the mod or try to make it compatible. 

I successfully could add Royal Armory and Heavy Armory by [PrivateEye](https://www.nexusmods.com/skyrimspecialedition/users/887024?tab=user+files).

[Skyrim SE Extended Weaponry](https://www.nexusmods.com/skyrimspecialedition/mods/2300) was not working with it so I removed it from my setup.
